"""Init tables

Revision ID: 4ee4a4c36df0
Revises: 6fc2e838bd90
Create Date: 2020-08-03 12:34:32.256492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee4a4c36df0'
down_revision = '6fc2e838bd90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
