"""new tables

Revision ID: 85c1d7ed9d93
Revises: 4ee4a4c36df0
Create Date: 2020-08-03 12:39:32.786076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c1d7ed9d93'
down_revision = '4ee4a4c36df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
