"""foreignkey added

Revision ID: d9d0ad724ab2
Revises: 1961f5ca0601
Create Date: 2020-08-03 12:50:41.321944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d0ad724ab2'
down_revision = '1961f5ca0601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_lists', ['task_list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'task_list_id')
    # ### end Alembic commands ###
